### ISSUE TITLE
This script does not report on pkgs that are used exclusively in Patch Management Policies

### ISSUE THREAD

**Issue by PJDunand** [jamf/Jamf-Pro-Object-LookUp#3]
This script does not report on pkgs that are used exclusively in Patch Management Policies and as such, does not generate a file at all.

Suggest including Patch Management Policies in the object lookup.

Preferably, we could get this feature request implemented. https://www.jamf.com/jamf-nation/feature-requests/75/display-policies-assigned-to-packages-scripts-and-groups

**Comment by daniel-maclaughlin** [comment]
Updated the script to check Patch Titles for specific packages. 
I can't speak to the Jamf Nation FR but hope the script acts as a substitute
